const poemData = [
    { text: "昔", py: "xī", zh: "从前，以前。", en: "In the past / formerly.", exam: true },
    { text: "孟子", py: "mèng zǐ", zh: "孟子，战国时期著名的思想家、儒家代表人物。", en: "Mencius." },
    { text: "少时", py: "shào shí", zh: "年少的时候，小时候。", en: "when he was young," },
    { text: "，", punc: true },
    { text: "父", py: "fù", zh: "父亲。", en: "his father" },
    { text: "早丧", py: "zǎo sàng", zh: "很早就去世了。", en: "passed away early," },
    { text: "，", punc: true },
    { text: "母", py: "mǔ", zh: "母亲。", en: "and his mother" },
    { text: "仉氏", py: "zhǎng shì", zh: "仉氏，孟子的母亲。", en: "Madame Zhang" },
    { text: "守节", py: "shǒu jié", zh: "守节，这里指丧夫后不再改嫁，独力抚养儿子。", en: "remained a widow." },
    { text: "。", punc: true },
    { text: "居住之所", py: "jū zhù zhī suǒ", zh: "居住的地方。“所”，处所、地方。", en: "The place where they lived" },
    { text: "近于", py: "jìn yú", zh: "靠近，接近。“于”，介词，靠近。", en: "was near" },
    { text: "墓", py: "mù", zh: "坟墓，墓地。", en: "a cemetery," },
    { text: "，", punc: true },
    { text: "孟子", py: "mèng zǐ", zh: "孟子。", en: "and Mencius" },
    { text: "学", py: "xué", zh: "模仿，学习。", en: "learned to imitate" },
    { text: "为", py: "wéi", zh: "做，举行。", en: "the practices of" },
    { text: "丧葬", py: "sāng zàng", zh: "出殡和埋葬的仪式。", en: "funeral and burial," },
    { text: "，", punc: true },
    { text: "躄", py: "bì", zh: "捶胸拍大腿（表示极度悲伤）。", en: "beating his chest," },
    { text: "、", punc: true },
    { text: "踊", py: "yǒng", zh: "跳跃（古代丧礼中因悲痛而跳跃的仪式）。", en: "stamping his feet," },
    { text: "痛哭", py: "tòng kū", zh: "伤心地大哭。", en: "and wailing in grief." },
    { text: "之", py: "zhī", zh: "助词，的。", en: "of" },
    { text: "事", py: "shì", zh: "事情，行为。", en: "matters." },
    { text: "。", punc: true },
    { text: "母", py: "mǔ", zh: "母亲。", en: "His mother" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：“", punc: true },
    { text: "此", py: "cǐ", zh: "这里。", en: "This" },
    { text: "非", py: "fēi", zh: "不是。", en: "is not" },
    { text: "所以", py: "suǒ yǐ", zh: "用来……的地方（特殊代词短语）。", en: "the place to", exam: true },
    { text: "居", py: "jū", zh: "居住，安置。", en: "raise", exam: true },
    { text: "子", py: "zǐ", zh: "孩子（指孟子）。", en: "my son.”" },
    { text: "也", py: "yě", zh: "表判断语气。", en: "(particle)" },
    { text: "。”", punc: true },
    { text: "乃", py: "nǎi", zh: "顺承连词，于是，就。", en: "So they", exam: true },
    { text: "去", py: "qù", zh: "离开（原先居住的地方）。", en: "left", exam: true },
    { text: "，", punc: true },
    { text: "遂", py: "suì", zh: "于是，就。", en: "and then" },
    { text: "迁居", py: "qiān jū", zh: "搬家，搬到……居住。", en: "moved to a house" },
    { text: "市旁", py: "shì páng", zh: "集市、集贸市场旁边。", en: "beside the marketplace." },
    { text: "。", punc: true },
    { text: "孟子", py: "mèng zǐ", zh: "孟子。", en: "Mencius" },
    { text: "又", py: "yòu", zh: "又，再次。", en: "again" },
    { text: "嬉", py: "xī", zh: "游戏，玩耍。", en: "played at imitating", exam: true },
    { text: "为", py: "wéi", zh: "做。", en: "the deeds of" },
    { text: "贾人", py: "gǔ rén", zh: "商人，买卖人。", en: "merchants," },
    { text: "炫卖", py: "xuàn mài", zh: "夸耀着叫卖，沿街叫卖货物。", en: "shouting and advertising goods for sale." },
    { text: "之", py: "zhī", zh: "的。", en: "of" },
    { text: "事", py: "shì", zh: "事情。", en: "matters." },
    { text: "。", punc: true },
    { text: "母", py: "mǔ", zh: "母亲。", en: "His mother" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：“", punc: true },
    { text: "此", py: "cǐ", zh: "这里。", en: "This" },
    { text: "又", py: "yòu", zh: "又。", en: "also" },
    { text: "非", py: "fēi", zh: "不是。", en: "is not" },
    { text: "所以", py: "suǒ yǐ", zh: "用来……的地方。", en: "the place to" },
    { text: "居", py: "jū", zh: "居住。", en: "raise" },
    { text: "子", py: "zǐ", zh: "孩子。", en: "my son.”" },
    { text: "也", py: "yě", zh: "表判断语气。", en: "(particle)" },
    { text: "。”", punc: true },
    { text: "舍", py: "shě", zh: "动词，放弃，离开。", en: "They left", exam: true },
    { text: "市", py: "shì", zh: "集市。", en: "the marketplace," },
    { text: "，", punc: true },
    { text: "近于", py: "jìn yú", zh: "靠近。", en: "and settled near" },
    { text: "屠", py: "tú", zh: "屠宰场，宰杀牲畜的地方。", en: "a slaughterhouse," },
    { text: "，", punc: true },
    { text: "学", py: "xué", zh: "学习，模仿。", en: "where he learned" },
    { text: "为", py: "wéi", zh: "做。", en: "to imitate" },
    { text: "买卖", py: "mǎi mài", zh: "做生意做买卖。", en: "bargaining" },
    { text: "屠杀", py: "tú shā", zh: "宰杀牲畜。", en: "and slaughtering animals." },
    { text: "之", py: "zhī", zh: "的。", en: "of" },
    { text: "事", py: "shì", zh: "事情。", en: "matters." },
    { text: "。", punc: true },
    { text: "母", py: "mǔ", zh: "母亲。", en: "His mother" },
    { text: "又", py: "yòu", zh: "又。", en: "again" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：“", punc: true },
    { text: "是", py: "shì", zh: "指示代词，这，这里。", en: "This", exam: true },
    { text: "亦", py: "yì", zh: "也。", en: "also" },
    { text: "非", py: "fēi", zh: "不是。", en: "is not" },
    { text: "所以", py: "suǒ yǐ", zh: "用来……的地方。", en: "the place to" },
    { text: "居", py: "jū", zh: "居住。", en: "raise" },
    { text: "子", py: "zǐ", zh: "孩子。", en: "my son" },
    { text: "矣", py: "yǐ", zh: "语气助词，了。", en: "either.”" },
    { text: "。”", punc: true },
    { text: "继而", py: "jì ér", zh: "接着，不久以后。", en: "Subsequently, they", exam: true },
    { text: "迁于", py: "qiān yú", zh: "搬家到……。“于”，到。", en: "moved near" },
    { text: "学宫", py: "xué gōng", zh: "学宫，古代的学校。", en: "a school (academy)" },
    { text: "之", py: "zhī", zh: "的。", en: "side." },
    { text: "旁", py: "páng", zh: "旁边。", en: "旁" },
    { text: "。", punc: true },
    { text: "每月", py: "měi yuè", zh: "每个月。", en: "On the first" },
    { text: "朔望", py: "shuò wàng", zh: "朔（农历初一）和望（农历十五）。", en: "and fifteenth days of every lunar month,", exam: true },
    { text: "，", punc: true },
    { text: "官员", py: "guān yuán", zh: "朝廷官员。", en: "government officials" },
    { text: "入", py: "rù", zh: "进入。", en: "would enter" },
    { text: "文庙", py: "wén miào", zh: "文庙，祭祀孔子的庙宇。", en: "the Confucian Temple," },
    { text: "，", punc: true },
    { text: "行礼", py: "xíng lǐ", zh: "举行祭祀礼仪。", en: "performing ceremonies," },
    { text: "跪拜", py: "guì bài", zh: "跪下磕头拜祭。", en: "kneeling, bowing," },
    { text: "，", punc: true },
    { text: "揖让", py: "yī ràng", zh: "揖让，拱手行礼，互相谦让。", en: "and exchanging courteous gestures" },
    { text: "进退", py: "jìn tuì", zh: "进退，指引礼仪时的进退规矩。", en: "of advancing and retreating." },
    { text: "，", punc: true },
    { text: "孟子", py: "mèng zǐ", zh: "孟子。", en: "Mencius" },
    { text: "见了", py: "jiàn le", zh: "看见了这些场景。", en: "saw this," },
    { text: "，", punc: true },
    { text: "一一", py: "yī yī", zh: "逐个地，全都。", en: "and practiced and memorized" },
    { text: "习记", py: "xí jì", zh: "模仿练习并记在心里。", en: "every single movement." },
    { text: "。", punc: true },
    { text: "孟母", py: "mèng mǔ", zh: "孟子的母亲。", en: "Mencius's mother" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：“", punc: true },
    { text: "此", py: "cǐ", zh: "这里。", en: "This" },
    { text: "真", py: "zhēn", zh: "真正，确实。", en: "is truly" },
    { text: "可以", py: "kě yǐ", zh: "可以，能够。", en: "the ideal place to" },
    { text: "居", py: "jū", zh: "居住，抚养。", en: "raise" },
    { text: "子", py: "zǐ", zh: "孩子。", en: "my son" },
    { text: "也", py: "yě", zh: "表判断语气。", en: "indeed.”" },
    { text: "。”", punc: true },
    { text: "遂", py: "suì", zh: "于是，就。", en: "So they completely" },
    { text: "居于此", py: "jū yú cǐ", zh: "定居在这里。", en: "settled down at this place." },
    { text: "。", punc: true }
];
